**IMPORTING DATASET**

In [42]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
df=pd.read_csv("/content/StressLevelDataset.csv")
df

anxiety_level  self_esteem  mental_health_history  depression  headache  \
0                14           20                      0          11         2   
1                15            8                      1          15         5   
2                12           18                      1          14         2   
3                16           12                      1          15         4   
4                16           28                      0           7         2   
...             ...          ...                    ...         ...       ...   
1095             11           17                      0          14         3   
1096              9           12                      0           8         0   
1097              4           26                      0           3         1   
1098             21            0                      1          19         5   
1099             18            6                      1          15         3   

      blood_pressure  sleep_quality  breathing_problem  noise_level  \
0                  1              2                  4            2   
1                  3              1                  4            3   
2                  1              2                  2            2   
3                  3              1                  3            4   
4                  3              5                  1            3   
...              ...            ...                ...          ...   
1095               1              3                  2            2   
1096               3              0                  0            0   
1097               2              5                  2            2   
1098               3              1                  4            3   
1099               3              0                  3            3   

      living_conditions  ...  basic_needs  academic_performance  study_load  \
0                     3  ...            2                     3           2   
1                     1  ...            2                     1           4   
2                     2  ...            2                     2           3   
3                     2  ...            2                     2           4   
4                     2  ...            3                     4           3   
...                 ...  ...          ...                   ...         ...   
1095                  2  ...            3                     2           2   
1096                  1  ...            4                     0           1   
1097                  3  ...            4                     5           1   
1098                  1  ...            1                     2           5   
1099                  0  ...            3                     3           4   

      teacher_student_relationship  future_career_concerns  social_support  \
0                                3                       3               2   
1                                1                       5               1   
2                                3                       2               2   
3                                1                       4               1   
4                                1                       2               1   
...                            ...                     ...             ...   
1095                             2                       3               3   
1096                             1                       1               1   
1097                             4                       1               3   
1098                             1                       4               1   
1099                             3                       3               1   

      peer_pressure  extracurricular_activities  bullying  stress_level  
0                 3                           3         2             1  
1                 4                           5         5             2  
2                 3                           2         2             1 

**BASIC PROPERTIES**

In [43]:
df.size

23100

In [44]:
df.shape

(1100, 21)

In [45]:
df.isnull().sum()

anxiety_level                   0
self_esteem                     0
mental_health_history           0
depression                      0
headache                        0
blood_pressure                  0
sleep_quality                   0
breathing_problem               0
noise_level                     0
living_conditions               0
safety                          0
basic_needs                     0
academic_performance            0
study_load                      0
teacher_student_relationship    0
future_career_concerns          0
social_support                  0
peer_pressure                   0
extracurricular_activities      0
bullying                        0
stress_level                    0
dtype: int64

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   anxiety_level                 1100 non-null   int64
 1   self_esteem                   1100 non-null   int64
 2   mental_health_history         1100 non-null   int64
 3   depression                    1100 non-null   int64
 4   headache                      1100 non-null   int64
 5   blood_pressure                1100 non-null   int64
 6   sleep_quality                 1100 non-null   int64
 7   breathing_problem             1100 non-null   int64
 8   noise_level                   1100 non-null   int64
 9   living_conditions             1100 non-null   int64
 10  safety                        1100 non-null   int64
 11  basic_needs                   1100 non-null   int64
 12  academic_performance          1100 non-null   int64
 13  study_load                    110

In [47]:
df.describe()

anxiety_level  self_esteem  mental_health_history   depression  \
count    1100.000000  1100.000000            1100.000000  1100.000000   
mean       11.063636    17.777273               0.492727    12.555455   
std         6.117558     8.944599               0.500175     7.727008   
min         0.000000     0.000000               0.000000     0.000000   
25%         6.000000    11.000000               0.000000     6.000000   
50%        11.000000    19.000000               0.000000    12.000000   
75%        16.000000    26.000000               1.000000    19.000000   
max        21.000000    30.000000               1.000000    27.000000   

          headache  blood_pressure  sleep_quality  breathing_problem  \
count  1100.000000     1100.000000    1100.000000        1100.000000   
mean      2.508182        2.181818       2.660000           2.753636   
std       1.409356        0.833575       1.548383           1.400713   
min       0.000000        1.000000       0.000000           0.000000   
25%       1.000000        1.000000       1.000000           2.000000   
50%       3.000000        2.000000       2.500000           3.000000   
75%       3.000000        3.000000       4.000000           4.000000   
max       5.000000        3.000000       5.000000           5.000000   

       noise_level  living_conditions  ...  basic_needs  academic_performance  \
count  1100.000000        1100.000000  ...  1100.000000           1100.000000   
mean      2.649091           2.518182  ...     2.772727              2.772727   
std       1.328127           1.119208  ...     1.433761              1.414594   
min       0.000000           0.000000  ...     0.000000              0.000000   
25%       2.000000           2.000000  ...     2.000000              2.000000   
50%       3.000000           2.000000  ...     3.000000              2.000000   
75%       3.000000           3.000000  ...     4.000000              4.000000   
max       5.000000           5.000000  ...     5.000000              5.000000   

        study_load  teacher_student_relationship  future_career_concerns  \
count  1100.000000                   1100.000000             1100.000000   
mean      2.621818                      2.648182                2.649091   
std       1.315781                      1.384579                1.529375   
min       0.000000                      0.000000                0.000000   
25%       2.000000                      2.000000                1.000000   
50%       2.000000                      2.000000                2.000000   
75%       3.000000                      4.000000                4.000000   
max       5.000000                      5.000000                5.000000   

       social_support  peer_pressure  extracurricular_activities     bullying  \
count     1100.000000    1100.000000                 1100.000000  1100.000000   
mean         1.881818       2.734545                    2.767273     2.617273   
std          1.047826       1.425265                    1.417562     1.530958   
min          0.000000       0.000000                    0.000000     0.000000   
25%          1.000000       2.000000                    2.000000     1.000000   
50%          2.000000       2.000000                    2.500000     3.000000   
75%          3.000000       4.000000                    4.000000     4.000000   
max          3.000000       5.000000                    5.000000     5.000000   

       stress_level  
count   1100.000000  
mean       0.996364  
std        0.821673  
min        0.000000  
25%        0.000000  
50%        1.000000  
75%        2.000000  
max        2.000000  

[8 rows x 21 columns]

**FEATURE SELECTION**

In [48]:
X=df.drop(['stress_level'],axis=1)
X

anxiety_level  self_esteem  mental_health_history  depression  headache  \
0                14           20                      0          11         2   
1                15            8                      1          15         5   
2                12           18                      1          14         2   
3                16           12                      1          15         4   
4                16           28                      0           7         2   
...             ...          ...                    ...         ...       ...   
1095             11           17                      0          14         3   
1096              9           12                      0           8         0   
1097              4           26                      0           3         1   
1098             21            0                      1          19         5   
1099             18            6                      1          15         3   

      blood_pressure  sleep_quality  breathing_problem  noise_level  \
0                  1              2                  4            2   
1                  3              1                  4            3   
2                  1              2                  2            2   
3                  3              1                  3            4   
4                  3              5                  1            3   
...              ...            ...                ...          ...   
1095               1              3                  2            2   
1096               3              0                  0            0   
1097               2              5                  2            2   
1098               3              1                  4            3   
1099               3              0                  3            3   

      living_conditions  safety  basic_needs  academic_performance  \
0                     3       3            2                     3   
1                     1       2            2                     1   
2                     2       3            2                     2   
3                     2       2            2                     2   
4                     2       4            3                     4   
...                 ...     ...          ...                   ...   
1095                  2       2            3                     2   
1096                  1       3            4                     0   
1097                  3       4            4                     5   
1098                  1       1            1                     2   
1099                  0       4            3                     3   

      study_load  teacher_student_relationship  future_career_concerns  \
0              2                             3                       3   
1              4                             1                       5   
2              3                             3                       2   
3              4                             1                       4   
4              3                             1                       2   
...          ...                           ...                     ...   
1095           2                             2                       3   
1096           1                             1                       1   
1097           1                             4                       1   
1098           5                             1                       4   
1099           4                             3                       3   

      social_support  peer_pressure  extracurricular_activities  bullying  
0                  2              3                           3         2  
1                  1              4                           5         5  
2                  2              3                           2         2  
3                  1              4                           4         5  
4                  1              5                           0       

In [49]:
Y=df['stress_level']
Y

0       1
1       2
2       1
3       2
4       1
       ..
1095    1
1096    2
1097    0
1098    2
1099    2
Name: stress_level, Length: 1100, dtype: int64

**SPLITTING DATA**

In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

**STANDARDIZING DATA**

In [51]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)
X_train=pd.DataFrame(X_train,columns=X.columns)
X_test=pd.DataFrame(X_test,columns=X.columns)


**MODELING DATA**

In [52]:
#IMPORTING LIBRARIES
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [53]:
#RANDOM FOREST CLASSIFIER
rf=RandomForestClassifier(n_estimators=100,criterion='gini',max_depth=3)
rf.fit(X_train,Y_train)
rf_pred=rf.predict(X_test)

In [54]:
#K-NEAREST NEIGHBOR CLKASSIFIER
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)
knn_pred = knn.predict(X_test)

In [55]:
#DECISION TREE CLASSIFIER
DT=DecisionTreeClassifier(criterion='gini',splitter='best',max_features=3,max_depth=3)
DT.fit(X_train,Y_train)
DecisionTreeClassifier(max_depth=3,max_features=3)
DT_pred=DT.predict(X_test)


In [56]:
#SUPPORT VECTOR MACHINE CLASSIFIER
svm = SVC()
svm.fit(X_train, Y_train)
svm_pred = svm.predict(X_test)

In [57]:
#LOGISTIC REGRESSION CLASSIFIER
log=LogisticRegression()
log.fit(X_train,Y_train)
log_pred=log.predict(X_test)

In [58]:
#NAIVE BAYES CLASSIFICATION
naive_bayes = GaussianNB()
naive_bayes.fit(X_train, Y_train)
nb_pred = naive_bayes.predict(X_test)

**MODEL EVALUATION**

In [59]:
from sklearn.metrics import accuracy_score
print("ACCURACY SCORES\n")
print("RANDOM FOREST :",accuracy_score(Y_test,rf_pred))
print("KNN :",accuracy_score(Y_test, knn_pred))
print("DECISION TREE :",accuracy_score(Y_test,DT_pred))
print("SVM Accuracy:", accuracy_score(Y_test, svm_pred))
print("logistic regression :", accuracy_score(Y_test, log_pred))
print("naive bayes :", accuracy_score(Y_test, nb_pred))

ACCURACY SCORES

RANDOM FOREST : 0.896969696969697
KNN : 0.8787878787878788
DECISION TREE : 0.8909090909090909
SVM Accuracy: 0.8909090909090909
logistic regression : 0.9030303030303031
naive bayes : 0.6121212121212121


In [60]:
from sklearn.metrics import confusion_matrix
print("CONFUSION MATRICES\n")
print("RANDOM FOREST :\n",confusion_matrix(Y_test,rf_pred))
print("KNN :\n",confusion_matrix(Y_test, knn_pred))
print("DECISION TREE :\n",confusion_matrix(Y_test,DT_pred))
print("SVM :\n", confusion_matrix(Y_test, svm_pred))
print("logistic regression :\n",confusion_matrix(Y_test, log_pred))
print("naive bayes:\n", confusion_matrix(Y_test, nb_pred))

CONFUSION MATRICES

RANDOM FOREST :
 [[100   4   9]
 [  3  93  11]
 [  5   2 103]]
KNN :
 [[96 11  6]
 [ 5 98  4]
 [ 8  6 96]]
DECISION TREE :
 [[ 94   0  19]
 [  2  92  13]
 [  2   0 108]]
SVM :
 [[102   3   8]
 [  9  94   4]
 [ 11   1  98]]
logistic regression :
 [[100   6   7]
 [  6  96   5]
 [  3   5 102]]
naive bayes:
 [[100  13   0]
 [  5 102   0]
 [ 10 100   0]]


In [61]:
from sklearn.metrics import precision_score
print("PRECISION-SCORES\n")
print("RANDOM FOREST :",precision_score(Y_test,rf_pred,average='weighted'))
print("KNN :",precision_score(Y_test, knn_pred, average='weighted'))
print("DECISION TREE :",precision_score(Y_test,DT_pred, average='weighted'))
print("SVM :",precision_score(Y_test, svm_pred, average='weighted'))
print("logistic regression :",precision_score(Y_test, log_pred, average='weighted'))
print("naive bayes:",precision_score(Y_test, nb_pred, average='weighted'))

PRECISION-SCORES

RANDOM FOREST : 0.9007836432817955
KNN : 0.8797823817724322
DECISION TREE : 0.9098330241187385
SVM : 0.8942668572645155
logistic regression : 0.9033053860673368
naive bayes: 0.45158684928149034


In [62]:
from sklearn.metrics import recall_score
print("RECALL-SCORES\n")
print("RANDOM FOREST :",recall_score(Y_test,rf_pred, average='weighted'))
print("KNN :",recall_score(Y_test, knn_pred, average='weighted'))
print("DECISION TREE :",recall_score(Y_test,DT_pred, average='weighted'))
print("SVM :", recall_score(Y_test, svm_pred, average='weighted'))
print("logistic regression :",recall_score(Y_test, log_pred, average='weighted'))
print("naive bayes :", recall_score(Y_test, nb_pred, average='weighted'))

RECALL-SCORES

RANDOM FOREST : 0.896969696969697
KNN : 0.8787878787878788
DECISION TREE : 0.8909090909090909
SVM : 0.8909090909090909
logistic regression : 0.9030303030303031
naive bayes : 0.6121212121212121


In [63]:
from sklearn.metrics import f1_score
print("F1-SCORES\n")
print("RANDOM FOREST :",f1_score(Y_test,rf_pred, average='weighted'))
print("KNN :",f1_score(Y_test, knn_pred, average='weighted'))
print("DECISION TREE :",f1_score(Y_test,DT_pred, average='weighted'))
print("SVM :",f1_score(Y_test, svm_pred, average='weighted'))
print("logistic regression :",f1_score(Y_test, log_pred, average='weighted'))
print("naive bayes :",f1_score(Y_test, nb_pred, average='weighted'))

F1-SCORES

RANDOM FOREST : 0.8973554933590032
KNN : 0.8787150787150787
DECISION TREE : 0.8929004176418499
SVM : 0.8915771099683918
logistic regression : 0.9029708279708278
naive bayes : 0.5057928087676371


**INTERPRETATION :**

In all above metrics,Logistic Regression holds a slight bit of prediction higher than all other models.


**so,logistic regression is  best suited for this dataset**